metadata:
- appName: microservice-provider2
  dataId: microservice-provider2
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: microservice-provider4
  dataId: microservice-provider4
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: microservice-provider3
  dataId: microservice-provider3
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: microservice-provider1
  dataId: microservice-provider1
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: microservice-consumer2
  dataId: microservice-consumer2
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: microservice-consumer1
  dataId: microservice-consumer1
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: microservice-gateway
  dataId: microservice-gateway
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
